export default [
  {
    title: 'Constant Moderato',
    artist: 'Mitsukiyo',
    id: 'SHkF48SgiSA',
    start: 0.1,
    end: 137,
  },
  {
    title: 'Luminous Memory',
    artist: 'Mitsukiyo',
    id: 'D3boxTP-ZG8',
    start: 0.1,
    end: 136,
  },
  {
    title: 'Mischievous Step',
    artist: 'Mitsukiyo',
    id: 'FHW2fNPaHU4',
    start: 0.1,
    end: 150,
  },
  {
    title: 'Lovely Picnic',
    artist: 'Mitsukiyo',
    id: 'hbYXXaaE9F0',
    start: 360,
    end: 485,
  },
  {
    title: 'Colorful Mess',
    artist: 'KARUT',
    id: 'OF9cu3cutj0',
    start: 0.1,
    end: 111,
  },
  {
    title: 'Funky Road',
    artist: 'KARUT',
    id: 'hbYXXaaE9F0',
    start: 703,
    end: 833,
  },
  {
    title: 'Unwelcome School',
    artist: 'Mitsukiyo',
    id: 'pEg_d2f6myw',
    start: 0.1,
    end: 120,
  },
  {
    title: 'Shady Girls',
    artist: 'Mitsukiyo',
    id: 'v7s-gHSs-YM',
    start: 0.1,
    end: 154,
  },
  {
    title: 'Midsummer cat',
    artist: 'Mitsukiyo',
    id: 'jokHmrFq56E',
    start: 0.1,
    end: 139,
  },
  {
    title: 'Romantic Smile',
    artist: 'Mitsukiyo',
    id: 'EBnOCXXg91o',
    start: 0.1,
    end: 133,
  },
  {
    title: 'Connected Sky',
    artist: 'KARUT',
    id: 'DzhcJxrS5Z8',
    start: 0.1,
    end: 121,
  },
  {
    title: 'Shooting Stars',
    artist: 'KARUT',
    id: 'yfsqGCO_ZfM',
    start: 0.1,
    end: 116,
  },
  {
    title: 'Barrier',
    artist: 'KARUT',
    id: 'phqb4ifkTrE',
    start: 0.1,
    end: 124,
  },
  {
    title: 'Step by Step',
    artist: 'KARUT',
    id: 'kuacQoR4U8I',
    start: 0.1,
    end: 130,
  },
  {
    title: 'Honey Jam',
    artist: 'Mitsukiyo',
    id: 'x-2yKahdTpg',
    start: 0.1,
    end: 138,
  },
  {
    title: 'MX Adventure',
    artist: 'Mitsukiyo',
    id: 'hbYXXaaE9F0',
    start: 484,
    end: 595,
  },
  {
    title: 'Irasshaimase',
    artist: 'Mitsukiyo',
    id: 'jHSozMn7GgA',
    start: 0.1,
    end: 129,
  },
  {
    title: 'Mechanical JUNGLE',
    artist: 'KARUT',
    id: 'JhWiVeXf2JM',
    start: 0.1,
    end: 122,
  },
  {
    title: 'Virtual Storm',
    artist: 'KARUT',
    id: 'vCvjZB8PqMQ',
    start: 0.1,
    end: 125,
  },
  {
    title: 'Tech N Tech',
    artist: 'KARUT',
    id: 'bg0GKgxO9lo',
    start: 0.1,
    end: 123,
  },
  {
    title: 'Midnight Trip',
    artist: 'Nor',
    id: 'KopFUu0F4gk',
    start: 0.1,
    end: 92,
  },
  {
    title: 'Daily Routine 247',
    artist: 'Nor',
    id: 'fTW7D5u0HfE',
    start: 0.1,
    end: 115,
  },
  {
    title: 'Party Time',
    artist: 'Mitsukiyo',
    id: 'eGX7qsgX7js',
    start: 538,
    end: 616,
  },
  {
    title: 'Endless Carnival',
    artist: 'Mitsukiyo',
    id: 'eOUzJN-W-rE',
    start: 0.1,
    end: 142,
  },
  {
    title: 'Future Bossa',
    artist: 'Mitsukiyo',
    id: 'kiwWb_1KFKs',
    start: 0.1,
    end: 130,
  },
  {
    title: 'Lemonade Diary',
    artist: 'Mitsukiyo',
    id: 'WECXxQnpBPE',
    start: 0.1,
    end: 154,
  },
  {
    title: 'Fade Out',
    artist: 'KARUT',
    id: 'v6Zw9m89CS8',
    start: 0.1,
    end: 90,
  },
  {
    title: 'Plug and Play',
    artist: 'KARUT',
    id: 'UqKlf3sOo3I',
    start: 0.1,
    end: 127,
  },
  {
    title: 'Alert',
    artist: 'KARUT',
    id: 'EDJttssxhuA',
    start: 0.1,
    end: 118,
  },
  {
    title: 'CrossFire',
    artist: 'KARUT',
    id: 'AqBVDJDB0ps',
    start: 0.1,
    end: 114,
  },
  {
    title: 'Hello to Halo',
    artist: 'Nor',
    id: 'ai3lHklPdV0',
    start: 1,
    end: 105,
  },
  {
    title: 'GGF',
    artist: 'Nor',
    id: 'skr-e1x4wy4',
    start: 0.1,
    end: 111,
  },
  {
    title: 'Vivid Night',
    artist: 'Nor',
    id: 'hbYXXaaE9F0',
    start: 596,
    end: 703,
  },
  {
    title: 'Aoharu',
    artist: 'Nor',
    id: 'Oeedwk9oQLk',
    start: 0.1,
    end: 108,
  },
  {
    title: 'Morose Dreamer',
    artist: 'Mitsukiyo',
    id: 'bLCRlPmpzEs',
    start: 1,
    end: 141,
  },
  {
    title: 'Koi is Love',
    artist: 'Mitsukiyo',
    id: 'lzUS9plwjoQ',
    start: 0.1,
    end: 108,
  },
  {
    title: 'Aira',
    artist: 'Mitsukiyo',
    id: 'bLCRlPmpzEs',
    start: 141,
    end: 277,
  },
  {
    title: 'Guruguru Usagi',
    artist: 'Mitsukiyo',
    id: 'rpOxGU1CssA',
    start: 0.1,
    end: 137,
  },
  {
    title: 'Water Drop',
    artist: 'KARUT',
    id: '0vpYgve07W8',
    start: 0.1,
    end: 130,
  },
  {
    title: 'Neo City Dive',
    artist: 'KARUT',
    id: 'VjdZmDzbZzk',
    start: 0.1,
    end: 138,
  },
  {
    title: 'Interface',
    artist: 'KARUT',
    id: 'kvWf9z02tIw',
    start: 0.1,
    end: 116,
  },
  {
    title: 'Glitch Street',
    artist: 'KARUT',
    id: 'XOY9xsXeYWk',
    start: 0.1,
    end: 126,
  },
  {
    title: 'Han-nari',
    artist: 'Nor',
    id: 'tWZ5uRPurec',
    start: 1,
    end: 101,
  },
  {
    title: 'SAKURA PUNCH',
    artist: 'Nor',
    id: 'tWZ5uRPurec',
    start: 102,
    end: 225,
  },
  {
    title: 'SAKURA PUNCH (Hard Arrange)',
    artist: 'Nor',
    id: 'tWZ5uRPurec',
    start: 225,
    end: 347,
  },
  {
    title: 'Rolling beat',
    artist: 'Mitsukiyo',
    id: 'lKRgr_mO2jQ',
    start: 0.1,
    end: 151,
  },
  {
    title: 'Pixel Time',
    artist: 'Mitsukiyo',
    id: 'jLNikHtJUeA',
    start: 0.1,
    end: 130,
  },
  {
    title: 'Summer Bounce',
    artist: 'Mitsukiyo',
    id: 'lTjp3sGQ-NY',
    start: 0.1,
    end: 138,
  },
  {
    title: 'Colorful Beach',
    artist: 'Mitsukiyo',
    id: 'lTjp3sGQ-NY',
    start: 138,
    end: 262,
  },
  {
    title: 'Summer Bounce (Hard Arrange)',
    artist: 'KARUT',
    id: 'kENHnTLwoY8',
    start: 106,
    end: 218,
  },
  {
    title: 'PRST Academy',
    artist: 'Mitsukiyo',
    id: 'cTLVPXpKu-E',
    start: 0.1,
    end: 103,
  },
  {
    title: 'PRST Marching',
    artist: 'Mitsukiyo',
    id: 'cTLVPXpKu-E',
    start: 103,
    end: 239,
  },
  {
    title: 'Summertime Archive',
    artist: 'Mitsukiyo',
    id: 'kENHnTLwoY8',
    start: 0.1,
    end: 106,
  },
  {
    title: 'Oriental Drop',
    artist: 'KARUT',
    id: 'lu_oLWJg6ao',
    start: 0.1,
    end: 123,
  },
  {
    title: 'The Dragon Express',
    artist: 'KARUT',
    id: 'lu_oLWJg6ao',
    start: 123,
    end: 246,
  },
  {
    title: 'Bunny Bunny Carrot Carrot',
    artist: 'Mitsukiyo',
    id: 'YJUngIIbR-4',
    start: 0.1,
    end: 115,
  },
  {
    title: 'Jackpot 777',
    artist: 'KARUT',
    id: 'YJUngIIbR-4',
    start: 115,
    end: 228,
  },
  {
    title: 'OperationD',
    artist: 'Nor',
    id: 'zhkSWznNGlA',
    start: 0.1,
    end: 113,
  },
  {
    title: 'Nesno wons',
    artist: 'Mitsukiyo',
    id: 'aVKifR68kzQ',
    start: 0.01,
    end: 116,
  },
];
